### ISSUE TITLE
All Images of the Applications are replaced by random persons

### ISSUE THREAD

**Issue by 0xMDIV** [Squidly271/community.applications#13]
I saw that all the Images of the Icons of the Apps are replaced by random Persons suddenly.
Is that a Bug?

![chrome_tPBb5P7s3Q](https://github.com/Squidly271/community.applications/assets/37520351/e2b46000-83f8-4687-9df4-215be2e002ae)

**Comment by strongy** [comment]
it was the developers idea of a april fools joke that multiple people disagreed with

**Comment by Squidly271** [comment]
And something happens with CA every year

**Comment by 0xMDIV** [comment]
Well for new unraid users its kinda scary. Specialy with so many cve out there lol

**Comment by Squidly271** [comment]
I abandoned my original idea as I figured that everyone would think there was an actual issue
