### ISSUE TITLE
Invalid URL / Server Error Response

### ISSUE THREAD

**Issue by FreeWillyB** [Squidly271/community.applications#3]
Tried to update CA plugin. It wiped the old one away, but fails to install the new one. I keep getting the same "Invalid URL / Server error response" messages as shown below. This is on Unraid 6.6.3

> plugin: downloading: https://raw.github.com/Squidly271/community.applications/master/archive/community.applications-2019.02.18a-x86_64-1.txz ... failed (Invalid URL / Server error response)
> plugin: wget: https://raw.github.com/Squidly271/community.applications/master/archive/community.applications-2019.02.18a-x86_64-1.txz download failure (Invalid URL / Server error response)

**Comment by keifererikson** [comment]
Getting the exact same error on my end.

**Comment by FreeWillyB** [comment]
Weird. I tried the link a bit ago and I thought it had worked. But trying again just now, I'm getting "Error 503 Backend unavailable, connection timeout" in response.

**Comment by keifererikson** [comment]
Looks like a couple people added new pull requests that resolve this issue. Just needs to be approved I believe.
