### ISSUE TITLE
tar archive is corrupt 

### ISSUE THREAD

**Issue by Vinery** [Squidly271/community.applications#8]
I installed plugin on unraid 6.9.2, but something is wrong.

Unable to install /boot/config/plugins/community.applications/community.applications-2021.06.04-x86_64-1.txz: tar archive is corrupt (tar returned error code 2)

**Comment by Squidly271** [comment]
No it's not (tried it).  Your server isn't downloading the txz properly.  Try again (worst case, delete the .txz from /config/plugins/community.applications on the flash drive)
