### ISSUE TITLE
Download Plugin Proxy

### ISSUE THREAD

**Issue by lalasou** [Squidly271/community.applications#9]
proxy.cfg This works great! The app can be browsed normally
Great for areas with bad internet
But the plugin download still can't download
I found that the plugin download is calling usr/local/emhttp/plugins/dynamix.plugin.manager/scripts/plugin
If you want to download plugins, you can also use proxy.cfg

**Comment by lalasou** [comment]
Hopefully plugin downloads can also use proxies.
e.g. 'proxy.cfg'

**Comment by Squidly271** [comment]
You have to set up the proxy in the go file (/config/go) on the flash drive by adding

```
http_proxy=http://xxx:xxx
https_proxy=http://xxx:xxx
```

CA uses a more efficient way of handling downloads hence the additional file required by it.  CA is simply a front-end for the base OS functions and most things in the base require the above to function via a proxy

**Comment by lalasou** [comment]
> You have to set up the proxy in the go file (/config/go) on the flash drive by adding
> 
> http_proxy=http://xxx:xxx
> https_proxy=http://xxx:xxx
> CA uses a more efficient way of handling downloads hence the additional file required by it. CA is simply a front-end for the base OS functions and most things in the base require the above to function via a proxy



Can it be restarted?

**Comment by lalasou** [comment]
Can it be used without restarting?

**Comment by Squidly271** [comment]
IDK I don't use a proxy.

**Comment by lalasou** [comment]
It works this time
I modified /etc/wgetrc

https_proxy =http://192.168.10.58:10809/
http_proxy = http://192.168.10.58:10809/
use_proxy = on

Modify it after use
without restarting
